### ISSUE TITLE
AttributeError: 'module' object has no attribute 'DetectBondStereochemistry'

### ISSUE THREAD

**Issue by lqcata** [jensengroup/xyz2mol#10]
qiang@qli:~/Desktop/xyz2mol-master$ ls
acetate.xyz  chiral_stereo_test.xyz  ethane.xyz  LICENSE  README.md  test.py  xyz2mol.py
qiang@qli:~/Desktop/xyz2mol-master$ python xyz2mol.py  ethane.xyz 
Traceback (most recent call last):
  File "xyz2mol.py", line 432, in <module>
    mol = xyz2mol(atomicNumList, charge, xyz_coordinates, charged_fragments, quick)
  File "xyz2mol.py", line 408, in xyz2mol
    new_mol = chiral_stereo_check(new_mol)
  File "xyz2mol.py", line 392, in chiral_stereo_check
    Chem.DetectBondStereochemistry(mol,-1)
AttributeError: 'module' object has no attribute 'DetectBondStereochemistry'

**Comment by jhjensen2** [comment]
I don't get that error. What version of RDKit are you using? If your not using 2019.03.2
If you are using an older version, try the new one

from rdkit import rdBase
print(rdBase.rdkitVersion)

**Comment by lqcata** [comment]
> I don't get that error. What version of RDKit are you using? If your not using 2019.03.2
> If you are using an older version, try the new one
> 
> from rdkit import rdBase
> print(rdBase.rdkitVersion)

I think it is the version that caused the error because I  tried command: sudo apt-get install python-rdkit 
And got the 201603.5 version installed.

**Comment by jhjensen2** [comment]
OK, closing the issue
