### ISSUE TITLE
Failed to return the radical smiles at alpha-C (Second Issue)

### ISSUE THREAD

**Issue by lqcata** [jensengroup/xyz2mol#13]
Dear Prof. Jensen.

Following the previous issue about the SMILES of alpha-C radicals. I have tried the updated script. It works for part of the alpha-C radicals and there are still some can not be correctly represented. 

In the Dropbox shared link below, I have attached both the success and failed examples. Hoping this will do help to come up with a general way to solve this problem. 

https://www.dropbox.com/s/duuzciq2k9d2pnj/examples_for_xyz2mol.zip?dl=0

**Comment by jhjensen2** [comment]
Still no general way to solve the problem, but I added another fix. I'll keep this issue open for a while in case you find other problems

**Comment by jhjensen2** [comment]
Haven't heard anything so closing
