### ISSUE TITLE
Stranger case when convert xyz file to mol

### ISSUE THREAD

**Issue by L3viAckerman** [jensengroup/xyz2mol#16]
Thank you for your work! Your code helped me a lot. 
I have used xyz2mol for convert many file .xyz to mol in rdkit, but when I used it for some molecular in QM9 dataset, it return the result look strange and seem not correct.
![strange_mol_case](https://user-images.githubusercontent.com/33130456/69745914-ba242c00-1175-11ea-95eb-312217bcd2fe.png)

I have take a picture about this case. I used Rdkit for visualize the mol result and the mol have a H atom that not connect to any atoms. This is my  file (sorry for the extension of file, I must change to .txt to upload)
[dsgdb9nsd_059827.txt](https://github.com/jensengroup/xyz2mol/files/3898069/dsgdb9nsd_059827.txt)

Could you have an idea for this case?
Something seem wrong and I dont know how to fix.
Thank you a lot!

**Comment by jhjensen2** [comment]
I have made a new version that fixes this problem. Let me know if you find other problems

**Comment by L3viAckerman** [comment]
Hi, thank you for support me and fixxing this issues!
I have used your code for converting xyz file from QM9 dataset to mol in RDkit. And I did not face with previous problems. Converting file dsgdb9nsd_059827.xyz seem right but when converted other file xyz, such that H20 file, it return warning like 

> !!! Warning !!! Distance between atoms 2 and 1 (0.962107 A) is suspicious.

. And when I converted, I other file, I got an error like: 

> File "xyz2mol_fix.py", line 120, in clean_charges
    Chem.SanitizeMol(mol)
rdkit.Chem.rdchem.AtomValenceException: Explicit valence for atom # 4 C greater than permitted
![Screenshot from 2019-12-05 18-09-27](https://user-images.githubusercontent.com/33130456/70231861-c15ac380-178d-11ea-8c63-217141f78b7c.png)

I think that I did not use your code in the right way. Could you explain for me how to use your code right, plz. Thank you so much for helping me!
Ps: Here is the file that I got warning and problems.
[dsgdb9nsd_000003.txt](https://github.com/jensengroup/xyz2mol/files/3926587/dsgdb9nsd_000003.txt)
[dsgdb9nsd_000053.txt](https://github.com/jensengroup/xyz2mol/files/3926588/dsgdb9nsd_000053.txt)

**Comment by L3viAckerman** [comment]
> I have made a new version that fixes this problem. Let me know if you find other problems

Hi, thank you so much because of your work. When I run your new update, it is fine with the case that I reported, but many others, I return the Warning: 

> !!! Warning !!! Distance between atoms 2 and 1 (0.962107 A) is suspicious.
I think because I understand something wrong (sorry about that because I am newbie in Chem). Could you help me,  please!  Thank you so much!

**Comment by jhjensen2** [comment]
I think I know what's going on. It's just a warning so you're not doing anything wrong and the result should be just fine. I'll try to see if it is possible to turn the warning off, but it's in RDKit so I may not be able to.

**Comment by L3viAckerman** [comment]
> I think I know what's going on. It's just a warning so you're not doing anything wrong and the result should be just fine. I'll try to see if it is possible to turn the warning off, but it's in RDKit so I may not be able to.

Hi, I have been check all the results and they seem alright. Thank you so much !
