### ISSUE TITLE
Failure for Ruthenium complexes

### ISSUE THREAD

**Issue by akalikadien** [jensengroup/xyz2mol#21]
Hello, 

Thanks for the great script! I was trying to look if a method exists that could convert my complexes into SMILES format and happened to find this code.
 
In these particular complexes the Ru has a valency of 5 so I added these 2 lines to the script:
```
atomic_valence[44] = [5]
atomic_valence_electrons[44] = 8
``` 

**What I did:**
Then I had the XYZ file posted below and used the command `python3 xyz2mol.py examples/RuPNP.xyz --charge -0` after placing the XYZ file in the examples folder. When visualizing this result I noticed that it doesn't look like my original complex at all and was wondering if it is due to a mistake in my procedure or if there is a problem with these kind of complexes and SMILES conversion in general.

**Input**
RuPNP.xyz
```
59

Ru 15.3980042 10.5490630 5.2033603
H 16.9439317 10.7730840 5.4520114
P 15.7467822 10.3527306 2.9458026
P 14.9265047 11.3401653 7.3234641
O 16.0603873 7.6485323 5.7451690
N 14.2736536 12.1247227 4.6360560
C 14.5298784 11.5516168 2.2257427
H 14.8802410 11.9773868 1.2738167
H 13.6165897 10.9742169 2.0208314
C 14.2307908 12.6388847 3.2622000
H 14.9512548 13.4761988 3.1471242
H 13.2320531 13.0746795 3.0573791
C 13.7876659 13.1571420 5.5562860
H 12.8123790 13.5471668 5.2006236
H 14.4766243 14.0278764 5.5498860
C 13.6278365 12.6270450 6.9819159
H 12.6639566 12.1040191 7.0756667
H 13.6419961 13.4406238 7.7225548
C 16.2852502 12.2723648 8.2092159
H 15.8439149 12.6793921 9.1342785
C 17.4506661 11.3397622 8.5621893
H 17.8198203 10.8290013 7.6611655
H 17.1657364 10.5718051 9.2916701
H 18.2809748 11.9191043 8.9944284
C 16.7710910 13.4398232 7.3379693
H 17.6240801 13.9396163 7.8223041
H 15.9899998 14.1950917 7.1793382
H 17.0997678 13.0763378 6.3533387
C 14.0767878 10.2898563 8.6239594
H 13.1373135 10.0390773 8.1001085
C 14.7987023 8.9710750 8.9257662
H 15.7188447 9.1352633 9.5027507
H 15.0643092 8.4269478 8.0124229
H 14.1467697 8.3232460 9.5319371
C 13.7332503 11.0502086 9.9116889
H 13.0884044 10.4315338 10.5546623
H 13.2030242 11.9932364 9.7177824
H 14.6405895 11.2811454 10.4889444
C 15.3994234 8.7261483 2.0949264
H 16.1679274 8.0563431 2.5157924
C 14.0284390 8.1834535 2.5225436
H 13.9244905 8.1663091 3.6155495
H 13.8974136 7.1578248 2.1458085
H 13.2079949 8.7913866 2.1120321
C 15.5398019 8.7657253 0.5683917
H 16.5550882 9.0336455 0.2459060
H 14.8386391 9.4876193 0.1224554
H 15.3083298 7.7777050 0.1412298
C 17.4065070 10.8737300 2.2713575
H 17.3229432 10.8594744 1.1716855
C 17.7383451 12.3024017 2.7229766
H 17.7288895 12.3718898 3.8202981
H 17.0227734 13.0376813 2.3300824
H 18.7401961 12.5875695 2.3669701
C 18.4902053 9.8846383 2.7182649
H 18.3195573 8.8712523 2.3283327
H 18.5229301 9.8239489 3.8160972
H 19.4775347 10.2164776 2.3623808
C 15.8294397 8.7898140 5.5755584
```

**Output:** C[CH+]C.C[CH-]C.C[CH-]C.C[CH-]C.[CH2-]CN1CC[P-][RuH+5]1([P-2])C#[O+]

**Additional info:**
Operating system: CentOS Linux release 7.3.1611 (Core)
xyz2mol version 723a2fa1ae7b8175cdb61066580882fbcd770417 and x2m_env Anaconda environment was used 

Screenshots:

XYZ file
![image](https://user-images.githubusercontent.com/45177460/98272034-860dd980-1f88-11eb-9221-65cb307a1da6.png)
SMILES representation after using xyz2mol
![image](https://user-images.githubusercontent.com/45177460/98272113-9de55d80-1f88-11eb-9b21-7f889bbe9705.png)

**Comment by akalikadien** [comment]
Oh I forgot to mention, I also ran xyz2mol with the following arguments: `python3 xyz2mol.py examples/RuPNP.xyz --charge -0 --ignore-chiral --use-huckel` in this case the bonds are correct but the orientation of most of the atoms is off, is this expected?

**Output**
CC(C)[P+]1(C(C)C)CCN2CC\[P+\](C(C)C)(C(C)C)[RuH+5]21C[O-]

**Comment by jhjensen2** [comment]
Dearling with organometallic molecules is a bit complex and and something I am working on off and on. The current code is on GitHub in the `tm_comb` branch. I talk about the approach in this [video](https://youtu.be/HD6IpXMVKeo) ([slides](https://speakerdeck.com/jhjensen/dealing-with-organometallic-molecules-in-rdkit)).
