### ISSUE TITLE
typo?

### ISSUE THREAD

**Issue by mkrompiec** [jensengroup/xyz2mol#27]
python xyz2mol.py examples/acetate.xyz --charge -1
```
Traceback (most recent call last):
  File "/Users/michalkrompiec/xyz2mol/xyz2mol/xyz2mol.py", line 806, in <module>
    mols = xyz2mol(atoms, xyz_coordinates,
  File "/Users/michalkrompiec/xyz2mol/xyz2mol/xyz2mol.py", line 732, in xyz2mol
    for new_mol in new_mols:
NameError: name 'new_mols' is not defined
```
Looks like there is a typo in line 725 (introduced by the commit on Oct 2), which should be changed to:
`    new_mols = AC2mol(mol, AC, atoms, charge,`

**Comment by nbehrnd** [comment]
Possibly related to the observation by @mkrompiec, `xyz2mol.py` by commit 2021-10-02 (d78ab4d0) does not function in the anticipated way.  One that does work however is the earlier commit by Jan H. Hensen (2020-11-26, 08:36, ac47bce, «charge check in AC2mol») easily checked-out.

Actually, Linux Debian 12/bookworm (branch testing) provides all to resolve the dependencies to work with xyz2mol.  This includes RDKit; thankfully, the repackaged version provided by DebiChem corresponds to version 2021.09.2  ([tracker](https://tracker.debian.org/pkg/rdkit))).

**Comment by jhjensen2** [comment]
Sorry for the long delay on this! Typo is now fixed
