### ISSUE TITLE
About anonical hack

### ISSUE THREAD

**Issue by geekinglcq** [jensengroup/xyz2mol#6]
Hi, at the end of the code, why should we convert the molecule to Smiles string and then load mol from Smiles string? 
```py
    smiles = Chem.MolToSmiles(mol, isomericSmiles=True)
    m = Chem.MolFromSmiles(smiles)
    smiles = Chem.MolToSmiles(m, isomericSmiles=True)
```

**Comment by jhjensen2** [comment]
If I remember correctly, it is to ensure that you get identical SMILES regardless of the atom ordering in the xyz files. It shouldn't be necessary to do it twice but it is, which is why we call it a "hack"
