### ISSUE TITLE
segmentation fault of RDkit Get3DDistanceMatrix()

### ISSUE THREAD

**Issue by TermeHansen** [jensengroup/xyz2mol#8]
I get segmentation faults when using the Get3DDistanceMatrix function of RDkit (updated to latest stable of RDkit, and still getting the issue)

By changing 
`dMat = Chem.Get3DDistanceMatrix(mol)`
in xyz2AC
to 
`dMat = distance_matrix(xyz, xyz)`

and adding `from scipy.spatial import distance_matrix` in preamble I don't have any issues at all.

**Comment by jhjensen2** [comment]
I can't reproduce this using the conda version (2019.03.2) on Linux, and I'd rather not introduce a new dependency unless really needed. 

Can you send more details such as version number, OS? Are all molecules giving you trouble?

**Comment by TermeHansen** [comment]
Ahh yes I can see now that I debug a bit further down, that it is something internally on my environment. If I just import rdkit I have no problems, but when I also import some of my own scripts first I get the segmentation fault. So for sure not related to xyz2mol, and a specific bug for rdkit and my setup. I will investigate and post at rdkit development...

**Comment by jhjensen2** [comment]
OK, great. Closing this issue
